// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"userapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: UserapiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/get/:id",
				Handler: GetUserHandler(serverCtx),
			},
		},
	)
}
